package com.Bank;

import com.Bank.TransferRequest;
import com.Bank.AccountResponse;
import com.Bank.TransactionResponse;
import com.Bank.AccountService;
import com.Bank.TransferService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.math.BigDecimal;
import java.util.List;

/** Rest controller for controlling Account.
 * <p>
 *    Is api for account service's.
 * </p>
 *
 * @see TransferController
 * @author Valep Vinreo
 * @version 1.00
 * @since 04-2026
 *
 */
@RestController
@RequestMapping("/api/accounts")
@RequiredArgsConstructor
public class Account_Controller {

    private final AccountService accountService;
    private final TransferService transferService;

    /** Creating account by request from AccountService.
     *
     *
     * @param request Object with data for creating account(cannot be null).
     * @return new {@link ResponseEntity} with object {@link AccountResponse},{@link HttpStatus}
     */
    @PostMapping
    public ResponseEntity<AccountResponse> createAccount(@Valid @RequestBody AccountService.CreateAccountRequest request) {
        AccountResponse response = accountService.createAccount(request);
        return new ResponseEntity<>(response, HttpStatus.CREATED);
    }

    /** Getter for all accounts linked to the User
     *
     * @return {@link ResponseEntity} with {@link List} object's {@link AccountResponse}
     */
    @GetMapping
    public ResponseEntity<List<AccountResponse>> getUserAccounts() {
        List<AccountResponse> accounts = accountService.getUserAccounts();
        return ResponseEntity.ok(accounts);
    }

    /** Return account by entered account number.
     *
     * @param accountNumber unique autogenerated 20-digit number.
     * @see Account
     * @return {@link ResponseEntity} with object {@link AccountResponse}
     */
    @GetMapping("/{accountNumber}")
    public ResponseEntity<AccountResponse> getAccount(@PathVariable String accountNumber) {
        AccountResponse response = accountService.getAccountByNumber(accountNumber);
        return ResponseEntity.ok(response);
    }

    /** Return account balance through account number.
     *
     * @param accountNumber unique autogenerated 20-digit number.
     * @return {@link ResponseEntity} & {@link AccountResponse}
     */
    @GetMapping("/{accountNumber}/balance")
    public ResponseEntity<BigDecimal> getBalance(@PathVariable String accountNumber) {
        AccountResponse account = accountService.getAccountByNumber(accountNumber);
        return ResponseEntity.ok(account.getBalance());
    }

    /**
     * Closes a bank account (available to administrators and the account owner).
     * <p>
     * <b>Closing conditions:</b>
     * <ul>
     * <li>Account balance must be 0</li>
     * <li>No pending transactions</li>
     * <li>Account must not already be closed</li>
     * </ul>
     * </p>
     *
     * @param accountNumber account number to close
     * @return an empty response with code 204 (No Content)
     * <p>
     *  204 - Account successfully closed
     *  400 - Unable to close account (non-zero balance or active transactions)
     *  401 - User not authenticated
     *  403 - Not authorized to close account
     *  404 - Account not found
     */
    @DeleteMapping("/{accountNumber}")
    @PreAuthorize("hasRole('USER') or hasRole('ADMIN')")
    @Operation(summary = "Close account", description = "Closes a bank account (balance must be 0)")
    @ApiResponses({
            @ApiResponse(responseCode = "204", description = "Account closed successfully"),
            @ApiResponse(responseCode = "400", description = "Unable to close account (balance not 0 or active transactions)"),
            @ApiResponse(responseCode = "403", description = "No permission to close this account"),
            @ApiResponse(responseCode = "404", description = "Account not found")
    })
    public ResponseEntity<Void> closeAccount(@PathVariable String accountNumber) {
        accountService.closeAccount(accountNumber);
        return ResponseEntity.noContent().build();
    }
}
